HousePricePrediction/House_rent Pred by Django/House_Price_Prediction-project/House_Price_Prediction/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from getlocation.views import dependantfield
urlpatterns = [
    path('admin/', admin.site.urls),
    path('getlocation/', include('getlocation.urls',namespace='getlocation')),
    path('',views.home),
    path('predict/',views.predict,name='predict'),
    path('predict/result',views.result),
    
]


HousePricePrediction/House_rent Pred by Django/House_Price_Prediction-project/getlocation/urls.py
from django.urls import path
from . import views
from House_Price_Prediction.views import predict as predict_views
app_name='getlocation'
urlpatterns = [
    path('dependantfield/', views.dependantfield, name='dependantfield'),
    # Add other URLs specific to the 'getlocation' app here if needed
    
]


HousePricePrediction/House_rent Pred by Django/House_Price_Prediction-project/getlocation/models.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.name

class Divisions(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.name

class District(models.Model):
    division = models.ForeignKey(Divisions, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.name
    
class Upazila(models.Model):
    district=models.ForeignKey(District,on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.name
    

HousePricePrediction/House_rent Pred by Django/House_Price_Prediction-project/House_Price_Prediction/views.py
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from scipy.stats import t
import math,os

from django.shortcuts import render
def home(request):
    return render(request,"home.html")

def predict(request):
    return render(request,"predict.html")

def  result(request):
    path = r"D:\python project\House_rent Pred by Django\dataset\Clean_data.csv"
    rent_df = pd.read_csv(path)
    rent_df=rent_df.drop(columns=['Unnamed: 0'])
    x = rent_df.drop(columns=["Rent","Location"])
    y = rent_df["Rent"]

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

    # column_trans = make_column_transformer(
    #     (OneHotEncoder(sparse=False), ['Location']),
    #     remainder='passthrough'
    # )
    # column_trans,

    pipe = make_pipeline( StandardScaler(), DecisionTreeRegressor())
    pipe.fit(x_train, y_train)
    y_pred=pipe.predict(x_test)
    
    size = int(request.GET['size'])
    room = int(request.GET['room'])
    total_bathroom = int(request.GET['total bathroom'])
    attached_bathroom = int(request.GET['attached bathroom'])
    varanda = int(request.GET['varanda'])
    dinning = int(request.GET['dinning'])
    floor = int(request.GET['floor'])
    lift = int(request.GET['lift'])
    input_data = pd.DataFrame([[size, room, total_bathroom, attached_bathroom, varanda, dinning, floor, lift]],
                              columns=['Size', 'Room', 'Total Bathroom', 'Attached Bathroom', 'Varanda', 'Dining', 'Floor', 'Lift'])
    prediction = pipe.predict(input_data)[0]
    def calculate_prediction_interval(y_pred, rmse, confidence=0.50):
        df = len(y_pred) - 1
        std_error = rmse * np.sqrt(1 + 1/len(y_pred))
        t_statistic = t.ppf((1 + confidence) / 2, df=df)
        margin_of_error = t_statistic * std_error
        return margin_of_error
    Mse=mean_squared_error(y_test,y_pred)
    Rmse=math.sqrt(Mse)
    
    margin_error = calculate_prediction_interval(y_pred, Rmse)
    lower_bound=round(prediction-margin_error)
    upper_bound=round(prediction+margin_error)
    rent=f"The Predicted Rent is: TK {str(lower_bound)} - {str(upper_bound)}"

    return render(request,"predict.html",{"result2":rent}) 

HousePricePrediction/House_rent Pred by Django/House_Price_Prediction-project/getlocation/views.py

from django.shortcuts import render
from .models import Country, Divisions, District,Upazila

def dependantfield(request):
    countryid = request.GET.get('country', None)
    divisionid = request.GET.get('division', None)
    districtid=request.GET.get('district',None)
    upazilaid=request.GET.get('upazila',None)

    division = None
    district = None
    upazila=None
    if countryid:
        getcountry = Country.objects.get(id=countryid)
        division = Divisions.objects.filter(country=getcountry)
    if divisionid:
        getdivision = Divisions.objects.get(id=divisionid)
        district = District.objects.filter(division=getdivision)
        
    if districtid:
        getdistrict=District.objects.get(id=districtid)
        upazila=Upazila.objects.filter(district=getdistrict)
    country = Country.objects.all()
    return render(request, 'dependantfield.html', locals())

HousePricePrediction/House_rent Pred by Django/House_Price_Prediction-project/getlocation/templates/dependantfield.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>SELECT LOCATION </title>

     <style>
        /* Additional CSS Styles */
        .btn-primary {
            width: 200px; /* Adjust button width as needed */
            height: 50px; /* Adjust button height as needed */
        }

        .margin-top-10 {
            margin-top: 10px; /* Add margin from the top */
        }

            body {
        background-color:#40E0D0;
        background-image: linear-gradient(19deg, #21D4FD 0%, #B721FF 100%);
        font-family: 'Poppins', sans-serif;
        height: 100vh;
    }

    .custom-button {
            width: 200px; 
            height: 55px; 
            margin-top: 50px;
        }
       .increase-text-size {
            font-size: 30px; /* Adjust the font size as needed */
        }

                h3.text-center {
                color: #ffffff; /* Change to the desired text color */
                margin-top: 5rem; /* Adjust margin top as needed */
            }



        .auth {
    background-color: #000000;
    display: inline-block;
    position: absolute;
    top: 25%;
    right: 40%;
    transform: translate(20%, -20%);
    padding: 4rem;
    border-radius: 0.5rem;
    min-width: 70rem;
    max-width: 100rem;
}

    </style>

</head>
<body>
    <form  class="auth">
        <div class="container mt-10" style="width:50%">
            <h3 class="text-center mt-5 "> CHOOSE YOUR LOCATION  </h3>
            <label for="country">Country</label>
            <select class="form-select" aria-label="Default select example" id="country" onchange="countryfield()">
                <option selected>Choose Country</option>
                {% for i in country %}
                    <option value="{{i.id}}" {% if request.GET.country == i.id|lower %}selected{% endif %}>{{i.name}}</option>
                {% endfor %}
            </select>
            <br/>
            <label for="division">Divisions</label>
            <select class="form-select" aria-label="Default select example" id="division" onchange="divisionfield()">
                <option selected>Choose Division</option>
                {% for i in division %}
                    <option value="{{i.id}}" {% if request.GET.division == i.id|lower %}selected{% endif %}>{{i.name}}</option>
                {% endfor %}
            </select>
            <br/>
            <label for="district">District</label>
            <select class="form-select" aria-label="Default select example" id="district" onchange="districtfield()">
                <option selected>Choose District</option>
                {% for i in district %}
                    <option value="{{i.id}}" {% if request.GET.district == i.id|lower %}selected{% endif %}>{{i.name}}</option>
                {% endfor %}
            </select>
            <br/>

            <label for="Upazila">Upazila</label>
            <select class="form-select" aria-label="Default select example" id="upazila" >
                <option selected>Choose Upazila</option>
                {% for i in upazila %}
                    <option value="{{i.id}}">{{i.name}}</option>
                {% endfor %}
            </select>
            <br/>
        </div>
        <div class="text-center ">
             <a href="{% url "predict" %}" class="btn btn-success custom-button  increase-text-size " >Click Here </a>
        </div>

    </form>
<script>
    function countryfield(){
        var countryid = document.getElementById('country').value;
        window.location = "/getlocation/dependantfield/?country="+countryid;
    }
    function divisionfield(){
      var divisionid = document.getElementById('division').value;
      var countryid = document.getElementById('country').value; // Get country ID from country dropdown
      window.location = "/getlocation/dependantfield/?country=" + countryid + "&division=" + divisionid;
    }
    function districtfield(){
      var districtid = document.getElementById('district').value;
      var divisionid = document.getElementById('division').value;
      var countryid = document.getElementById('country').value; 
      window.location = "/getlocation/dependantfield/?country=" + countryid + "&division=" + divisionid  + "&district=" + districtid;
    }

    function districtfield(){
      var districtid = document.getElementById('district').value;
      var divisionid = document.getElementById('division').value;
      var countryid = document.getElementById('country').value; 
      window.location = "/getlocation/dependantfield/?country=" + countryid + "&division=" + divisionid  + "&district=" + districtid;
    }

</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

HousePricePrediction/House_rent Pred by Django/House_Price_Prediction-project/templates/home.html
{% comment %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>House Rent Prediction </title>
    <style>
      h1 {
        color: white;
        cursor: pointer;
      }
      body {
        font-family: Arial, sans-serif;
        margin-top: 270px;
        padding: 0;
        background-image: url("{%static 'balcony-witu-elegant-furniture-decoration-generative-ai.jpg' %}");
        background-attachment: fixed;
        background-size: cover;
      }
      input[type="submit"] {
        background-color: #000000;
        color: white;
        cursor: pointer;
        padding: 16px 32px;

      }
    </style>
  </head>
  <body style="text-align: center">
    <div>
      <h1>Welcome to House Prediction System </h1>
    </div>
    <div class=" mt-50 width-50px height-10px">
         <button type="button" class="btn btn-success">Let's start </button>
    </div>
  </body>
</html>

 {% endcomment %}

 {% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <title>House Rent Prediction</title>
        <style>
            body {
                margin-top: 270px;
                padding: 0;
                background-image: url("{% static 'balcony-witu-elegant-furniture-decoration-generative-ai.jpg' %}");
                background-attachment: fixed;
                background-size: cover;
            }

            .custom-button {
            width: 200px; 
            height: 57px; 
            margin-top: 50px;
        }

          .increase-text-size {
            font-size: 30px; /* Adjust the font size as needed */
        }

        </style>
    </head>
    <body style="text-align: center;">
        <div>
            <h1 class="text-white">Welcome to House Prediction System</h1>
        </div>
        <div class="mt-0.1">
            <a href="{% url "getlocation:dependantfield" %}" class="btn btn-primary custom-button  increase-text-size " >Let's start</a>
        </div>

        <!-- Bootstrap JS and dependencies -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
      </body>
</html>

HousePricePrediction/House_rent Pred by Django/House_Price_Prediction-project/templates/predict.html
s<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <link rel="icon" type="image/x-icon" href="data:image/x-icon;,">


    <title>House Rent Prediction </title>

    <script src="{% static "js/main.js" %}"> </script>
    <script src="https://kit.fontawesome.com/1af3d7e4a4.js" crossorigin="anonymous" ></script>

        <style>
                        @import url('https://fonts.googleapis.com/css?family=Poppins');
                * {
                    box-sizing: border-box;
                    padding: 0;
                    margin: 0;
                }

                html {
                    font-size: 10px;
                }

                body {
                    background-color: #0093E9;
                    background-image: linear-gradient(19deg, #21D4FD 0%, #B721FF 100%);
                    font-family: 'Poppins', sans-serif;
                    height: 100vh;
                }

             .result-text {
            font-size: 24px; /* Adjust the font size as needed */
        }


                .auth {
                    background-color: #ffffff;
                    display: inline-block;
                    position: absolute;
                    top: 25%;
                    right: 40%;
                    transform: translate(20%, -20%);
                    padding: 2rem;
                    border-radius: 0.5rem;
                    min-width: 70rem;
                    max-width: 89rem;
                }

                .auth h1 {
                    font-size: 2.5rem;
                    text-align: center;
                    padding-bottom: 2rem;
                    border-bottom: 0.1rem solid silver;
                }

                .auth form {
                    margin: 1rem;
                }

                .auth input {
                    width: 100%;
                    margin-top: 2rem;
                    height: 4rem;
                    font-size: 1.4rem;
                    border: none;
                    border-bottom: 0.15rem solid rgb(163, 163, 163);
                    padding: 0 0.5rem;
                    outline: none;
                }

                .auth input:hover {
                    border-bottom: 0.15rem solid #0086da;
                }

                .auth input::placeholder {
                    color: rgb(163, 163, 163);

                }

                .auth form p {
                    font-size: 1.3rem;
                    padding: 3rem 0 0 0.5rem;
                    color: rgb(163, 163, 163);
                    font-weight: bold;
                }

                .auth form p:hover {
                    color: rgb(80, 80, 80);
                    cursor: pointer;
                }

                .auth input[type="submit"]{
                    background-color: #000000;
                    color: white;
                    cursor: pointer;
                    padding: 16px 32px;
                }

                .row h2.result2{
                background-color: #000000;
                color: white;
                cursor: pointer;
                padding: 40px 50px;
                font-size: 1.8rem;
                font-weight: bold;
                margin-top: 280px; 
                border-radius: 8px;
                    }

                

        </style>
</head>

<body>
    <section>
        <div class="auth">
            <h1 class="row " style="text-align:center; margin-top: 40px;  ">House Rent Prediction </h1>
            <form action="result">
                <input type="text" name="size" id="size" placeholder="Enter The Size " autocomplete="off" required>
                <input type="text" name="room" id="room" placeholder="Enter Room Number " required>
                <input type="text" name="total bathroom" id="total bathroom" placeholder="Enter Total Bathroom" required>
                <input type="text" name="attached bathroom" id="attached bathroom" placeholder="Enter Attached Bathroom Number " required>
                <input type="text" name="varanda" id="varanda" placeholder="Enter Varanda number " required>
                <input type="text" name="dinning" id="dinning" placeholder="Enter Dinning number" required>
                <input type="text" name="floor" id="floor" placeholder="Enter Floor number " required>
                <input type="text" name="lift" id="lift" placeholder="Enter Lift number" required>
                <input type="submit" value="PREDICT">
                </br>
                <div class="row" style="text-align:center; margin-top: 20px;">
                      <h2 class="result-text" > {{result2}} </h2>
                </div>
            </form>
            
        </div>
    </section>

</body>

</html>